module.exports = {
	yes: [
		"y",
		"yes",
		"yep",
		"k",
		"okay",
		"ok",
		"yeah",
		"oh yeah",
		"definitely",
		"yes please",
		"let's go",
		"of course",
		"sure",
		"sounds good",
	],
	no: ["n", "no", "nah", "no thanks", "definitely not"],
	restart: ["restart", "reset", "start over"],
	status: ["status", "show", "show board", "where were we", "show me"],
	commands: ["commands", "show commands", "command", "options"],
	difficulty: [
		"difficulty 0",
		"difficulty 1",
		"difficulty 2",
		"difficulty 3",
		"level 0",
		"level 1",
		"level 2",
		"level 3",
	],
};
